thisdir = class/Facades/System.Runtime.Numerics
SUBDIRS = 
include ../../../build/rules.make

LIBRARY_SUBDIR = Facades
LIBRARY_INSTALL_DIR = $(mono_libdir)/mono/$(FRAMEWORK_VERSION)/Facades

LIBRARY = System.Runtime.Numerics.dll
LIB_MCS_FLAGS = --force-runtime:v4 /r:System.Numerics

NO_TEST = yes

include ../../../build/library.make
