thisdir = class/Facades/System.Diagnostics.Tools
SUBDIRS = 
include ../../../build/rules.make

LIBRARY_SUBDIR = Facades
LIBRARY_INSTALL_DIR = $(mono_libdir)/mono/$(FRAMEWORK_VERSION)/Facades

LIBRARY = System.Diagnostics.Tools.dll
LIB_MCS_FLAGS = --force-runtime:v4 /r:System

NO_TEST = yes

include ../../../build/library.make
